# --- Image & runtime ---
image:
  repository: rocketpool/smartnode
  tag: v1.20.2
  pullPolicy: IfNotPresent

network: testnet
smartnodeVersion: v1.20.2

replicaCount: 1
podAnnotations: {}
podLabels: {}

resources:
  requests:
    cpu: "200m"
    memory: "512Mi"
  limits: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  fsGroupChangePolicy: OnRootMismatch

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

nodeSelector: {}
tolerations: []
affinity: {}



# Smartnode daemon (rocketpoold) entrypoint.
command: ["/go/bin/rocketpool"]
args: ["--settings=/data/.rocketpool/user-settings.yml", "node"]

clients:
  executionHttpUrl: http://el-geth-rpc:8545
  executionWsUrl: ws://el-geth-rpc:8546
  beaconHttpUrl: http://cl-lighthouse-api:5052

walletPassword:
  existingSecret: ""
  existingSecretKey: password
  filePath: /data/.rocketpool/data/password

# --- Persistence ---
persistence:
  enabled: true
  storageClass: "local-storage-ssd"   # adapt to your default class
  accessModes: ["ReadWriteOnce"]
  size: 50Gi
  existingClaim: ""                   # if you want to bind an existing PVC
  volumeMode: "Filesystem"             # or "Block" if you use raw block storage
  volumeName: "rocketpool-smartnode"       # specify a particular PV to bind to
  mountPath: /data/.rocketpool  # where to mount the volume in the container

# --- Service ---
service:
  type: ClusterIP
  annotations: {}
  labels: {}
  ports:
    api:
      enabled: true
      port: 8080
      targetPort: 8080
    metrics:
      enabled: true
      port: 9102
      targetPort: 9102

# --- ServiceMonitor (Prometheus Operator) ---
serviceMonitor:
  enabled: false
  namespace: ""       # where your Prometheus Operator expects ServiceMonitors
  interval: 30s
  scrapeTimeout: 10s
  additionalLabels: {}
