root:
  executionClientMode: external
  executionClient: geth
  consensusClientMode: external
  externalConsensusClient: lighthouse
  isNative: "true"
  rpDir: {{ .Values.persistence.mountPath }}
  version: {{ .Values.smartnodeVersion | quote }}
  useFallbackClients: "false"
  reconnectDelay: 60s
  enableMetrics: "true"
  enableODaoMetrics: "false"
  ecMetricsPort: "9105"
  bnMetricsPort: "9100"
  vcMetricsPort: "9101"
  nodeMetricsPort: "9102"
  exporterMetricsPort: "9103"
  watchtowerMetricsPort: "9104"
  enableBitflyNodeMetrics: "false"
  enableMevBoost: "false"
  enableCommitBoost: "false"
  enableIPv6: "false"

smartnode:
  projectName: rocketpool
  dataPath: {{ .Values.persistence.mountPath }}/data
  network: {{ .Values.network | quote }}
  apiPort: "8080"
  manualMaxFee: "0"
  priorityFee: "2"
  distributeThreshold: "1"
  rewardsTreeMode: download
  archiveECUrl: ""
  verifyProposals: "false"

externalExecution:
  httpUrl: {{ .Values.clients.executionHttpUrl | quote }}
  wsUrl: {{ .Values.clients.executionWsUrl | quote }}

externalLighthouse:
  httpUrl: {{ .Values.clients.beaconHttpUrl | quote }}
  doppelgangerDetection: "true"
  containerTag: sigp/lighthouse:v8.0.0

native:
  consensusClient: lighthouse
  validatorRestartCommand: {{ .Values.persistence.mountPath }}/restart-vc.sh
  validatorStopCommand: {{ .Values.persistence.mountPath }}/stop-validator.sh
