apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rocketpool-smartnode.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "rocketpool-smartnode.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  user-settings.yml: |
{{- $configPath := printf "config/%s/user-settings.yml" .Values.config.profile }}
{{ required (printf "missing Rocket Pool config file: %s" $configPath) (.Files.Get $configPath) | nindent 4 }}
      
