{{- if  .Values.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rocketpool-smartnode.fullname" . }}-data
  labels:
    app.kubernetes.io/name: {{ include "rocketpool-smartnode.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes: {{ toYaml .Values.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
{{- if .Values.persistence.volumeMode }}
  volumeMode: {{ .Values.persistence.volumeMode | quote }}
{{- end }}
{{- if .Values.persistence.volumeName }}
  volumeName: {{ .Values.persistence.volumeName | quote }}
{{- end }}
{{- end }}
